# Generated by Django 2.2.8 on 2020-03-27 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametermodel',
            old_name='Thrid_Parameter',
            new_name='Third_Parameter',
        ),
    ]
